apiVersion: v1
kind: Service
metadata:
  name: nashgo-service
spec:
  type: NodePort
  ports:
  - name: "nashgo-httpd"
    port: 80
    protocol: TCP
    nodePort: 32499
  selector:
    role: nashgo